project_id = "iqbmuqsegahpxpxolkjr"

[functions.setup-admin]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-change-password]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true
